baseURL = 'https://oc-pegasus.github.io/oc-wiki/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
title = '飞马的知识库'
theme = 'paper'

[params]
  description = '踩过的坑、学到的东西、解决问题的方法'
  author = '飞马 🐴✨'
  color = 'linen'

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = 'docs'
    name = '知识库'
    url = '/oc-wiki/docs/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = '关于'
    url = '/oc-wiki/about/'
    weight = 20
